### ISSUE TITLE
Resources commitment to develop Immersive Web Geo-alignment feature (add to IMWWG charter)

### ISSUE THREAD

**Issue by cperey** [w3c/immersive-web-wg-charter#44]
On January 11, during the IMWWG meeting, we agreed to collaboratively explore in our respective directions to identify at least two businesses who will commit to support the development of the geo-alignment feature and, through their commitments, make the case that the geo-alignment feature needs to stay in the W3C IMWWG charter. 

I shared the status and the above need with the members of the OGC GeoPose SWG. Five companies pledged their support. They are: 

- Open Site Plan (Steve Smyth is the president)
- Ethar (Tony Hodgson is the CEO)
- OnSite Viewer (Jan-Erik Vinje is CEO)
- Global Nomads (Nazih Fino is CEO)
- Away Team (Rob Smith is CEO)

All are members of OGC in good standing. All have development teams qualified to work on the feature. I know that at least Rob Smith is a W3C member via the OGC Spatial Data on the Web WG. I do not know the membership status of the others. 

Can someone please assist us to take appropriate steps to ensure that the volunteers are able to contribute?

Also, please provide feedback about any other resources that could be available for the Geo-Alignment feature work.

**Comment by himorin** [comment]
I confirm that Rob Smith is W3C Invited Experts (not a W3C member) at Spatial Data on the Web Working Group.

**Comment by cperey** [comment]
Thanks for checking. Is it required that resources for this feature be full W3C members (in other words, are W3C invited experts not sufficiently credentialed for the role?)?

**Comment by himorin** [comment]
The Invited Experts status is managed per each WG. So if someone who is an Invited Experts in other WG would want to contribute at the IWWG, one need to apply to an Invited Experts separately.

**Comment by janerivi** [comment]
Hi, I'm Jan-Erik Vinje Co-chair of the OGC GeoPose SWG, and managing Director of Open AR Cloud and also the CEO/CTO of the geospatial AR cloud company OnSiteViewer. It would be perfect for our bussiness model to have GeoPose support directly in web browsers. OnSiteViewer would be happy to contribute to code efforts to demonstrate such functionality in a browser.

**Comment by rjksmith** [comment]
I'm Rob Smith - IE in [Spatial Data on the Web WG](https://www.w3.org/2021/sdw/) - and I'm leading the development of [Web Video Map Tracks (WebVMT)](https://w3c.github.io/sdw/proposals/geotagging/webvmt/) for synchronising location with video for the web.

Geo-alignment seems directly applicable to WebVMT in order to surface the video camera's geolocation and orientation in a web browser, and I'm keen to integrate this feature with existing WebVMT support code - including the [demos at webvmt.org](https://webvmt.org/webvmt/demos).

**Comment by NazihFino** [comment]
Hi, I'm Nazih Fino founder, and developer of Global Nomad GIS Services, member of the OGC GeoPose SWG, and partner of Open AR Cloud. Global Nomad would be happy to the Geo-alignment code efforts to demonstrate such functionality in a browser.

**Comment by Yonet** [comment]
Thank you for opening the issue @cperey and organizing interested parties. @janerivi @rjksmith @NazihFino thank you for your interest and commitment. For IW to commit to this work, we need at least 2 people from different companies, who are willing to be the contact person and work on the draft. You can join Immersive Web Community Group and work on the [incubation repo](https://github.com/immersive-web/geo-alignment). Is this something you are interested in doing? @himorin is there anything else you would like to add?

Thanks!

**Comment by himorin** [comment]
@Yonet Since this is a discussion for WG charter, membership to CG does not have any effective position to discussion/contribution nor voting. Only participants to WG can have right to vote or contribute (of course, comments are welcome at anytime from anyone), so one need to join the WG first even if it is an IE status at the WG.

**Comment by AdaRoseCannon** [comment]
I think for now it's fine for the work to continue in the CG for Geo Pose, and for it to go into the charter as long as there is intent to move it into the WG before the end of this charter. It will need a commitment from a WG member to be able to continue the work in the WG.

**Comment by cperey** [comment]
@ada I believe you are proposing that the CG work on the geo-alignment until such a point that it is ready for the WG to review/vote on. That’s clear to me. 

Regardless of where the work happens, we must make sure that there’s not a conflation between OGC GeoPose and the IW Geo-alignment feature. 

While they both pertain to geospatial domain, they are very different: one is an OGC standard which can enable the other (development of an IW feature supporting geo-alignment).

Thank you for your attention to these distinctions.

Can you please confirm that you have sufficient information to keep (return) geo-alignment in the next charter? 

If you do not have sufficient information to include geo-alignment, can you please provide details on what is missing?

**Comment by AdaRoseCannon** [comment]
@cperey yes sorry I mean Geo Alignment that's what I get for sending emails immediately before lunch

**Comment by AdaRoseCannon** [comment]
We have sufficient information, it would be best if we had WG members but I think Invited Experts could possibly suffice for now until it needs to become a standard when it will need the participants to be a member of the group and also to find an implementor. I will talk with the other chairs tomorrow to see if they are happy to proceed.

**Comment by Yonet** [comment]
> Can you please confirm that you have sufficient information to keep (return) geo-alignment in the next charter

@cperey we do have sufficient information. What we are trying to get is someone to own and work on the [Geo-alignment](https://github.com/immersive-web/geo-alignment) on our group. Currently there is no work being done on our repo, therefor no discussion is happening around Geo Data. As we tried to meet during TPAC but there was no interest in the meeting because there were no discussions happening on our group.
Since you kindly made introductions, I'm asking if anyone is willing to be the owner of the Geo-alignment feature and work on the spec. If we do not have anyone working on the spec, does it make sense to add it to our charter description? 
Is there anything I am missing?

**Comment by cperey** [comment]
@Yonet I don't see Geo-alignment feature on the agenda for the Feb 8 meeting. 

Is that because this issue is about ONLY the charter for the IM WG and the WG will not entertain the Geo-alignment until after the work has been done in the CG? I thought that it (Geo-alignment feature) was/is going to be included in the new charter.

Sorry, I see now that the proposers of this work have "overlooked" your explicitly asking WHO is willing to be the owner of the Geo-alignment feature and work on the spec.  Those who have pledged support will be meeting in a few hours and I will push for the nomination of one person for the group (at minimum to manage the repository). 

Have you heard anything back from stakeholders in your organization about support for this feature?

**Comment by himorin** [comment]
@cperey it's listed as administrvia#166, due that this repository is out from immersive-web organization where bot can run.

**Comment by ethar-tone** [comment]
Greetings, All. I'm Tony Hodgson, CEO of Ethar, Inc. and want to add my company's support to this repo. 

**Ethar, Inc.**, and our mother-company, **Brainwaive LLC**, have been supportive of the W3C and Web standards for several years, beginning with our  participation in the original **IWCG/IWWG TPAC 2018**. Members of our team audited a majority of the alternating IWWG / IWCG calls over the coming two years, and attended the **Jan 2019 FTF** meeting at Samsung Research in Mountain View. In addition, with our focus on AR for enterprise applications, we’ve been the principal investigator and team lead on multiple immersive web and spatial computing projects and formal publications aligned with the intention of WebXR:

[[Web-Based AR for Enterprise Applications: Technical Report](https://thearea.org/web-based-ar-for-enterprise-applications/)] for the AR for Enterprise Alliance (AREA): 2020.
Web-Based AR for Enterprise Applications: Current and Future Adoption. 2020.
Web-Based AR for Enterprise Applications: A Prototype Implementation. 2020.
[Wearable Enterprise AR Security: Security Framework and Tests Protocol](https://thearea.org/area-resources/wearable-enterprise-ar-security-report/). 2017. 
Geospatial Data Integration in AR Solutions for Electric Utilities (EPRI). 2020/2021
Brainwaive is the [Founding Sponsor of the Open AR Cloud Association (OARC](https://www.openarcloud.org/)): 2019.
Contributor to the OARC [State of The AR Cloud Report - 2019](https://www.openarcloud.org/reports/sotarc-2019). 
Voting member of the [IEEE P2874 Spatial Web working group](https://standards.ieee.org/project/2874.html).
Code contributions to [OGC Testbed 17](https://www.ogc.org/projects/initiatives/t17) to enable Web-based AR/VR visualization of GIS data through the OGC API. 

We're currently developing WebXR-based experiences for a variety of customers, and contributing to the OGC GeoPose specification. We look forward to collaborating with you all on WebXR-aligned reference implementations leveraging GeoPose.

**Comment by Yonet** [comment]
Thank you @ethar-tone for all the info. We have the [geo-aligntment repository](https://github.com/immersive-web/geo-alignment/issues) on Immersive Web org. Please join the discussion on the issues there. 

@cperey we have added the geo-alignment to the WG charter description but it is not one of our deliverables in the next 2 years since there haven't been sufficient CG work on it yet. Once we reach to a certain maturity level and if there is interest, we might end up moving the spec to WG faster. Refer to [W3C Process doc](https://www.w3.org/2021/Process-20211102/) to read more about the process. 

Closing this issue. Please continue any geo-alignment discussion on it's [repo]([geo-aligntment repository](https://github.com/immersive-web/geo-alignment/issues). Thanks!
